# Generated by Django 6.1 on 2026-09-04 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_backfill_blank_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date']},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user__first_name', 'user__username']},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['user__first_name', 'user__username']},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='backend.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='backend.patient'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='backend.patient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='backend.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='backend.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_in', to='backend.medicine'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.prescription'),
        ),
    ]
