# Generated by Django 6.1 on 2026-09-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auditlog_billitem_doctorschedule_medicinestock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='backend.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('dispensed', 'Dispensed')], default='issued', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='instructions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
