# Generated by Django 6.1 on 2026-09-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_prescription_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('in_person', 'In person'), ('online', 'Online')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='average_consult_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_status',
            field=models.CharField(choices=[('in_clinic', 'In clinic'), ('on_break', 'On a break'), ('running_late', 'Running late'), ('unavailable', 'Unavailable today')], default='in_clinic', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='status_note',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('checked_in', 'Checked in'), ('in_consultation', 'In consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
