# Generated by Django 6.1 on 2026-09-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_appointment_consultation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
